services:
  jupyter:
    build: .
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--notebook-dir=/app", "--ServerApp.token=''", "--ServerApp.disable_check_xsrf=True"]

  etl-bronze:
    build: .
    container_name: etl_bronze_only
    volumes:
      - .:/app
    command: ["python", "main.py", "--bronze-only"]
    profiles: ["etl"]

  etl-full:
    build: .
    container_name: etl_full_pipeline
    volumes:
      - .:/app
    command: ["python", "main.py"]
    profiles: ["etl"]

  etl-silver:
    build: .
    container_name: etl_silver_only
    volumes:
      - .:/app
    command: ["python", "main.py", "--layer", "silver", "--timestamp", "${TIMESTAMP}"]
    profiles: ["etl"]

  etl-gold:
    build: .
    container_name: etl_gold_only
    volumes:
      - .:/app
    command: ["python", "main.py", "--layer", "gold", "--timestamp", "${TIMESTAMP}"]
    profiles: ["etl"]
